apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command: ["cloudflared", "tunnel", "run"]
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared/config.yml
          subPath: config.yml
          readOnly: true
        - name: cloudflared-credentials
          mountPath: /etc/cloudflared/credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
      - name: cloudflared-credentials
        secret:
          secretName: cloudflared-credentials
