apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
        args: ["--config", "/etc/cloudflared/config.yml", "--token", "$(TUNNEL_SERVICE_TOKEN_SECRET)"]
        env:
        - name: TUNNEL_SERVICE_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudflared-tunnel
              key: client-secret
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
