apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        # Run the tunnel by its UUID or name:
        command: ["cloudflared", "tunnel", "run", "007a56dd-6217-4e42-89bf-f7262ba4bb03"]
        volumeMounts:
        # Mount config:
        - name: config
          mountPath: /etc/cloudflared/config.yml
          subPath: config.yml
          readOnly: true
        # Mount credentials:
        - name: credentials
          mountPath: /etc/cloudflared/credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      - name: credentials
        secret:
          secretName: cloudflared-credentials
