apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/JulienGiguere/homelab.git
    path: .
    targetRevision: HEAD
    directory:
      recurse: true
      include: "{**/*.argoapp.yaml,**/*.argoapp.yml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
