global:
  domain: argocd.jg1g.com

server:
  insecure: true
  ingress:
    enabled: false

  extraArgs:
    - --insecure

  service:
    type: ClusterIP

  config:
    admin.enabled: true
    url: https://argocd.jg1g.com

configs:
  cm:
    create: true
    url: https://argocd.jg1g.com
    kustomize.buildOptions: --enable-helm

dex:
  enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true