apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: authentik
  namespace: authentik
resources:
  - resources/certificate.yaml
  - resources/httpproxy.yaml
helmCharts:
  - name: authentik
    version: "2025.2.1"
    repo: "https://charts.goauthentik.io"
    releaseName: "authentik"
    namespace: authentik
    valuesFile: "helm/values.yaml"
