apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: authentik
  namespace: authentik
resources:
  - resources/certificate.yaml
  - resources/ingress.yaml
  - resources/middleware.yaml