apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tailscale
  name: tailscale-subnet-router
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tailscale
  name: tailscale-subnet-router
subjects:
- kind: ServiceAccount
  name: tailscale-subnet-router
  namespace: tailscale
roleRef:
  kind: Role
  name: tailscale-subnet-router
  apiGroup: rbac.authorization.k8s.io