image:
  repository: ghcr.io/onedr0p/lidarr
  tag: 1.1.4.3027
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8686

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: /config
    existingClaim: lidarr-config-nfs-pvc

  media:
    enabled: true
    mountPath: /downloads
    existingClaim: media-pvc

env:
  TZ: "America/Montreal"
