image:
  repository: linuxserver/deluge
  tag: version-2.0.3-2201906121747ubuntu18.04.1
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

service:
  port:
    port: 8112

ingress:
  main:
    enabled: false
    
persistence:
  config:
    enabled: true
    mountPath: /config
    existingClaim: deluge-config-pvc

  downloads:
    enabled: true
    mountPath: /media
    existingClaim: media-pvc

addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.30.0
        pullPolicy: IfNotPresent

    env:
      PORT_FORWARDING_ENABLED: "true"
      VPN_SERVICE_PROVIDER: "mullvad"
      TZ: "America/Montreal"

dnsConfig:
  options:
    - name: ndots
      value: "1"

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Montreal"
  UMASK_SET: "022"
  DELUGE_LOGLEVEL: "info"
