image:
  repository: linuxserver/deluge
  tag: version-2.0.3-2201906121747ubuntu18.04.1
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

service:
  port:
    port: 8112

ingress:
  main:
    enabled: false
    
persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: local-path
    mountPath: /config

  downloads:
    enabled: true
    mountPath: /downloads
    existingClaim: media-pvc

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Montreal"
  UMASK_SET: "022"
  DELUGE_LOGLEVEL: "info"
