apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: auth.jg1g.com
  dnsNames:
    - auth.jg1g.com