apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flaresolverr
  namespace: media

resources:
  - resources/ingress.yaml

helmCharts:
  - name: flaresolverr
    releaseName: flaresolverr
    repo: https://k8s-at-home.com/charts/
    version: 5.4.2
    valuesFile: helm/values.yaml
