apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
spec:
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - tv.jg1g.com