apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jg1g.com
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/juliengiguere/jg1g.com:latest
    argocd-image-updater.argoproj.io/webapp.update-strategy: digest
    argocd-image-updater.argoproj.io/webapp.pull-secret: pullsecret:argocd/ghcr-clubcedille-secret
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jg1g.com
  source:
    repoURL: https://github.com/juliengiguere/homelab
    targetRevision: main
    path: apps/jg1g.com/prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
