image:
  repository: ghcr.io/flaresolverr/flaresolverr
  tag: v3.3.19
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8191

ingress:
  main:
    enabled: false

env:
  TZ: "America/Montreal"
