apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/juliengiguere/homelab
      targetRevision: main
      path: media/jellyseer
    - repoURL: https://github.com/juliengiguere/homelab
      targetRevision: main
      path: media/jellyseer/charts/jellyseerr-chart
      helm:
        valueFiles:
          - ../../helm/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true