apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: lidarr
  namespace: media

resources:
  - resources/ingress.yaml
  - resources/config-pvc.yaml

helmCharts:
  - name: lidarr
    releaseName: lidarr
    repo: https://k8s-at-home.com/charts/
    version: 4.5.2
    valuesFile: helm/values.yaml
