authentik:
  error_reporting:
    enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - auth.jg1g.com
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.jg1g.com

global:
  namespace: "authentik"
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_SECRET_KEY
    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_TOKEN
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_PASSWORD
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_POSTGRES_PASSWORD

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-secrets
    secretKeys:
        adminPasswordKey: AUTHENTIK_POSTGRES_PASSWORD
        userPasswordKey: AUTHENTIK_POSTGRES_PASSWORD
  persistence:
    enabled: true

redis:
  enabled: true
  persistence:
    enabled: truecurl -vk https://auth.jg1g.com