apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator-node-reader-binding
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale-operator-node-reader
  apiGroup: rbac.authorization.k8s.io