apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- argocd-ingress.yaml

patches:
- path: argocd-server-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
- path: argocd-cmd-params-cm-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cmd-params-cm
    version: v1
- patch: |-
    - op: remove
      path: /
  target:
    group: networking.k8s.io
    kind: Ingress
    name: argocd-server-ingress
    version: v1

